# Generated by Django 6.0.3 on 2026-04-05 06:54

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Collection Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CollectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Collection',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PiecePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Piece',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PieceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ImageField(upload_to='ceramics/pieces/')),
                ('stage', models.CharField(choices=[('greenware', 'Greenware'), ('bisque', 'Bisque Fire'), ('glaze', 'Final Glaze Fire')], max_length=20)),
                ('ai_stage_guess', models.CharField(blank=True, choices=[('greenware', 'Greenware'), ('bisque', 'Bisque Fire'), ('glaze', 'Final Glaze Fire')], help_text='Stage automatically detected by Claude', max_length=20)),
                ('ai_confidence', models.FloatField(blank=True, help_text='AI confidence score 0.0–1.0', null=True)),
                ('description', models.TextField(blank=True)),
                ('glaze_notes', models.TextField(blank=True, help_text="Claude's detailed glaze analysis: colour, sheen, texture, likely glaze type")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='ceramics.piecepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
