# Generated by Django 6.0.3 on 2026-04-05 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceramics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieceupdate',
            name='image',
        ),
        migrations.AlterField(
            model_name='pieceupdate',
            name='glaze_notes',
            field=models.TextField(blank=True, help_text='Short glaze name description, e.g. "Golden Hour yellow on body, Carmel and White Gloss on lid"'),
        ),
        migrations.CreateModel(
            name='PieceUpdateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ceramics/pieces/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ceramics.pieceupdate')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='ceramics/avatars/')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ceramics_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
