# Generated by Django 6.0.3 on 2026-04-05 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceramics', '0002_remove_pieceupdate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecepage',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start date'),
        ),
    ]
