# Generated by Django 6.0.3 on 2026-04-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceramics', '0003_piecepage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('temp', models.FloatField(default=0.0, help_text='Current temperature in °F')),
                ('cone_fire', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('firing', 'Firing'), ('cooling', 'Cooling'), ('done', 'Done')], default='idle', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
